config/routes.rb
Rails.application.routes.draw do
root 'top#main'
get 'top/main'
resources :products
resources :cart_items, only: [:create, :destroy]
resources :carts, only: [:show]
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :products
  has_many :cart_items, dependent: :destroy
end 

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :carts
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :carts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_cart

private
  def current_cart
    if session[:cart_id]
      cart = Cart.find(session[:cart_id])
    else
      cart = Cart.create
      session[:cart_id] = cart.id
      cart
    end
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
    def create
      cart_item = CartItem.new(
        qty: params[:qty],
        product_id: params[:product_id],
        cart_id: current_cart.id
        )
        cart_item.save
     redirect_to root_path
    end

  def destroy
    CartItem.find(params[:id]).destroy
    redirect_to root_path
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart_items = current_cart.cart_items
  end
end

app/controllers/products_controller.rb
 class ProductsController < ApplicationController
   def index
    @products = Product.all
   end

   def new
    @product = Product.new
   end

   def create
    @product = Product.new(
      name: params[:product][:name],
      price: params[:product][:price])
     if @product.save
      redirect_to products_path
     else
      render 'new'
     end
   end

   def destroy
    Product.find(params[:id]).destroy
    redirect_to products_path
   end
 end

app/controllers/top_controller.rb
class TopController < ApplicationController
	def main
			@products = Product.all
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/carts/show.html.erb
<% @cart_items.each do |e|%>
<% p = Product.find(e.product_id) %> 
<p>
		商品名<%= p.name %>
		価格<%= p.price %>
		数量<%= e.qty %>
		
			<%= link_to '削除', cart_item_path(e), method: :delete %>
</p>
 <%= ((p.price) * e.qty) %> 円
<% end %>

<p>

</p>

<p>
	<%= link_to '商品の一覧表示', root_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shopping</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/index.html.erb
<table border="1">

	<tr>
		<th>product_id</th>
		<th>商品名</th>
		<th>価格</th>
		<th>操作</th>
	</tr>

<% @products.each do |e| %>
	<tr>
		<td><%= e.id %></td>
		<td><%= e.name %></td>
		<td><%= e.price %></td>
		<td>
			<%= link_to '削除', product_path(e), method: :delete, data: { confirm: '削除していいですか？' } %>
		</td>
	</tr>

<% end %>

</table>

<p>
	<%= link_to '商品登録', new_product_path %>
</p>
<p>
	<%= link_to 'トップへ', root_path %>
</p>

app/views/products/new.html.erb
<% if @product.errors.present? %>
<h3>エラーがあります</h3>
<ul>
	<% @product.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
	<% end %>
</ul>
<% end %>

<%= form_for @product do |f| %>

<table>
	<tr>
		<td><%= f.label :name, '商品名' %></td>
		<td><%= f.text_field :name %></td>
	</tr>
	<tr>
		<td><%= f.label :price, '価格' %></td>
		<td><%= f.number_field :price %></td>
	</tr>
	<tr>
		<td colspan="2"><%= f.submit '登録' %></td>
	</tr>
</table>

<% end %>

app/views/top/main.html.erb
helo
 <% @products.each do |e| %>
	<p>
		商品名<%= e.name %>
		価格<%= e.price %>円
		<%= form_tag cart_items_path(product_id: e.id) do %>
			数量: <%= text_field_tag :qty, 1, size: 2,style: 'text-align:right' %>
			<%= submit_tag "カートに入れる" %>
    <% end %>
	</p>
	<hr>
<% end %>	

	<p>
	<%= link_to "カートを見る", cart_path(current_cart.id) %>
	</p>
	
<p>
	<%= link_to '商品登録', new_product_path %>
</p>

<p>
	<%= link_to '商品一覧', products_path %>
</p>